version: '2'

services:
  db:
    image: drupaldocker/mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'True'
    networks:
      - back-tier
  php:
    image: drupaldocker/php
    networks:
      - back-tier
      - front-tier
    volumes:
      - ./conficker:/var/www/html
  app:
    image: drupaldocker/nginx
    networks:
      - front-tier
    ports:
      - 80
    volumes:
      - ./drupal.conf:/etc/nginx/conf.d/default.conf
      - ./conficker:/var/www/html
  drush:
    image: drupaldocker/drush
    networks:
      - back-tier
    volumes_from:
      - php

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
